(function(f,n){"object"===typeof exports&&exports&&"string"!==typeof exports.nodeName?n(exports):"function"===typeof define&&define.amd?define(["exports"],n):(f.Mustache={},n(f.Mustache))})(this,function(f){function n(a){return"function"===typeof a}function B(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$&")}function r(a,c){return null!=a&&"object"===typeof a&&c in a}function y(a,c){function b(a){"string"===typeof a&&(a=a.split(E,2));if(!z(a)||2!==a.length)throw Error("Invalid tags: "+a);
n=new RegExp(B(a[0])+"\\s*");m=new RegExp("\\s*"+B(a[1]));r=new RegExp("\\s*"+B("}"+a[1]))}if(!a)return[];var d=[],e=[],k=[],h=!1,g=!1,n,m,r;b(c||f.tags);for(var q=new x(a),u,l,t,w;!q.eos();){u=q.pos;if(t=q.scanUntil(n)){w=0;for(var v=t.length;w<v;++w)if(l=t.charAt(w),F.call(G,l)?g=!0:k.push(e.length),e.push(["text",l,u,u+1]),u+=1,"\n"===l){if(h&&!g)for(;k.length;)delete e[k.pop()];else k=[];g=h=!1}}if(!q.scan(n))break;h=!0;l=q.scan(H)||"name";q.scan(I);"="===l?(t=q.scanUntil(D),q.scan(D),q.scanUntil(m)):
"{"===l?(t=q.scanUntil(r),q.scan(J),q.scanUntil(m),l="&"):t=q.scanUntil(m);if(!q.scan(m))throw Error("Unclosed tag at "+q.pos);w=[l,t,u,q.pos];e.push(w);if("#"===l||"^"===l)d.push(w);else if("/"===l){l=d.pop();if(!l)throw Error('Unopened section "'+t+'" at '+u);if(l[1]!==t)throw Error('Unclosed section "'+l[1]+'" at '+u);}else"name"===l||"{"===l||"&"===l?g=!0:"="===l&&b(t)}if(l=d.pop())throw Error('Unclosed section "'+l[1]+'" at '+q.pos);return K(A(e))}function A(a){for(var c=[],b,d,e=0,k=a.length;e<
k;++e)if(b=a[e])"text"===b[0]&&d&&"text"===d[0]?(d[1]+=b[1],d[3]=b[3]):(c.push(b),d=b);return c}function K(a){for(var c=[],b=c,d=[],e,k=0,h=a.length;k<h;++k)switch(e=a[k],e[0]){case "#":case "^":b.push(e);d.push(e);b=e[4]=[];break;case "/":b=d.pop();b[5]=e[2];b=0<d.length?d[d.length-1][4]:c;break;default:b.push(e)}return c}function x(a){this.tail=this.string=a;this.pos=0}function v(a,c){this.view=a;this.cache={".":this.view};this.parent=c}function m(){this.cache={}}var L=Object.prototype.toString,
z=Array.isArray||function(a){return"[object Array]"===L.call(a)},F=RegExp.prototype.test,G=/\S/,M={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;","`":"&#x60;","=":"&#x3D;"},I=/\s*/,E=/\s+/,D=/\s*=/,J=/\s*\}/,H=/#|\^|\/|>|\{|&|=|!/;x.prototype.eos=function(){return""===this.tail};x.prototype.scan=function(a){a=this.tail.match(a);if(!a||0!==a.index)return"";a=a[0];this.tail=this.tail.substring(a.length);this.pos+=a.length;return a};x.prototype.scanUntil=function(a){a=this.tail.search(a);
var c;switch(a){case -1:c=this.tail;this.tail="";break;case 0:c="";break;default:c=this.tail.substring(0,a),this.tail=this.tail.substring(a)}this.pos+=c.length;return c};v.prototype.push=function(a){return new v(a,this)};v.prototype.lookup=function(a){var c=this.cache,b;if(c.hasOwnProperty(a))b=c[a];else{for(var d=this,e,k,h=!1;d;){if(0<a.indexOf("."))for(b=d.view,e=a.split("."),k=0;null!=b&&k<e.length;)k===e.length-1&&(h=r(b,e[k])),b=b[e[k++]];else b=d.view[a],h=r(d.view,a);if(h)break;d=d.parent}c[a]=
b}n(b)&&(b=b.call(this.view));return b};m.prototype.clearCache=function(){this.cache={}};m.prototype.parse=function(a,c){var b=this.cache,d=b[a];null==d&&(d=b[a]=y(a,c));return d};m.prototype.render=function(a,c,b){var d=this.parse(a);c=c instanceof v?c:new v(c);return this.renderTokens(d,c,b,a)};m.prototype.renderTokens=function(a,c,b,d){for(var e="",k,h,g,f=0,n=a.length;f<n;++f)g=void 0,k=a[f],h=k[0],"#"===h?g=this.renderSection(k,c,b,d):"^"===h?g=this.renderInverted(k,c,b,d):">"===h?g=this.renderPartial(k,
c,b,d):"&"===h?g=this.unescapedValue(k,c):"name"===h?g=this.escapedValue(k,c):"text"===h&&(g=this.rawValue(k)),void 0!==g&&(e+=g);return e};m.prototype.renderSection=function(a,c,b,d){function e(a){return f.render(a,c,b)}var f=this,h="",g=c.lookup(a[1]);if(g){if(z(g))for(var m=0,r=g.length;m<r;++m)h+=this.renderTokens(a[4],c.push(g[m]),b,d);else if("object"===typeof g||"string"===typeof g||"number"===typeof g)h+=this.renderTokens(a[4],c.push(g),b,d);else if(n(g)){if("string"!==typeof d)throw Error("Cannot use higher-order sections without the original template");
g=g.call(c.view,d.slice(a[3],a[5]),e);null!=g&&(h+=g)}else h+=this.renderTokens(a[4],c,b,d);return h}};m.prototype.renderInverted=function(a,c,b,d){var e=c.lookup(a[1]);if(!e||z(e)&&0===e.length)return this.renderTokens(a[4],c,b,d)};m.prototype.renderPartial=function(a,c,b){if(b&&(a=n(b)?b(a[1]):b[a[1]],null!=a))return this.renderTokens(this.parse(a),c,b,a)};m.prototype.unescapedValue=function(a,c){var b=c.lookup(a[1]);if(null!=b)return b};m.prototype.escapedValue=function(a,c){var b=c.lookup(a[1]);
if(null!=b)return f.escape(b)};m.prototype.rawValue=function(a){return a[1]};f.name="mustache.js";f.version="2.2.0";f.tags=["{{","}}"];var C=new m;f.clearCache=function(){return C.clearCache()};f.parse=function(a,c){return C.parse(a,c)};f.render=function(a,c,b){if("string"!==typeof a)throw c=TypeError,a=z(a)?"array":typeof a,new c('Invalid template! Template should be a "string" but "'+a+'" was given as the first argument for mustache#render(template, view, partials)');return C.render(a,c,b)};f.to_html=
function(a,c,b,d){a=f.render(a,c,b);if(n(d))d(a);else return a};f.escape=function(a){return String(a).replace(/[&<>"'`=\/]/g,function(a){return M[a]})};f.Scanner=x;f.Context=v;f.Writer=m});
var template='<div class="post"><div><h2><a href="/gag?p={{id}}">{{title}} </a></h2></div><div><img src=\'{{imgURL}}\'/></div><p class="stats"><span>{{likes}} points</span>&middot;<span><a href="/gag?p={{id}}"> comments</a></span></p><div class="actions"><div class="actions"><ul class="votes"><li class="btn border"><span class="fa fa-arrow-up"></span></li><li class="btn border"><span class="fa fa-arrow-down"></span></li></ul><ul><li class="btn border"><span class="fa fa-comment"></span></li></ul><ul class="social right"><li class="btn social facebook"><span class="fa fa-facebook" onclick="shareFacebook({{id}});">&nbsp;</span><span class="label">Facebook</span></li><li class="btn social twitter"><span class="fa fa-twitter" onclick="shareTwitter({{id}});">&nbsp;</span><span class="label">Twitter</span></li></ul></div></div></div><hr>',container=
document.querySelector(".stream");function get(f){if(f=(new RegExp("[?&]"+encodeURIComponent(f)+"=([^&]*)")).exec(location.search))return decodeURIComponent(f[1])}
function loadMore(){var f=window.location.protocol+"//"+window.location.host+window.location.pathname;isNaN(get("p"))?(p=1,history.pushState&&window.history.pushState("","",window.location.href+"?p=1")):p++;var n=new XMLHttpRequest;n.open("GET",f+"?p="+p+"&json",!0);n.onreadystatechange=function(){if(4===n.readyState&&200===n.status)for(var f=JSON.parse(n.responseText),r=0;r<f.length-1;r++){var y=Mustache.render(template,f[r]);console.log("loading->"+y);var A=document.createElement("div");A.innerHTML=
y;container.appendChild(A)}};n.send()}loadMore();